### ISSUE TITLE
Need an email callout graphic for Call Congress re: 215

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#55]
@cassiemc Erika's out so i'm flagging this for you -- though I know Monday is a Canadian holiday.... eek!
Hi there! We're hoping to send an email to core supporters asking them to call Congress. Launch day for the email is this coming Monday or Tuesday.

Here is the call now image we used for net neutrality for reference:
https://www.dropbox.com/s/kvmdbn6svjfujk3/mozilla-advocacy_net-neutrality-february-2015_email-call-out-04.png?dl=0

The only change we need is to change "tell your elected officials to protect net neutrality" to "tell your elected officials to stop mass surveillance"

Everything else can stay the same.

**Comment by cassiemc** [comment]
Ok cool. @lovegushwa Can you take this on (since monday is not a holiday for you?) You can prioritize this over your other engagement work. I doubt we have the original source file so would just need to recreate the styles. The guidelines for Sandstone (the theme used on this) are here if you need colors or anything, but just sounds like a simple text change. https://www.mozilla.org/en-US/styleguide/websites/sandstone/colors/

**Comment by lovegushwa** [comment]
Hi @valianttry & @cassiemc  
Here is the updated email asset. Let me know if you need anything else!
https://www.dropbox.com/s/tertt5ukv0s5w15/mozilla-advocacy_mass-surveillance-may-2015_email-call-out.png?dl=0

![mozilla-advocacy_mass-surveillance-may-2015_email-call-out](https://cloud.githubusercontent.com/assets/12228435/7663402/ab94692e-fb1e-11e4-983d-16c47cd2a9eb.png)

**Comment by valianttry** [comment]
@lovegushwa  Whoohooo! Thanks SO much for the speediness on this! :clap: :clap:

**Comment by cassiemc** [comment]
Yes thank you @lovegushwa much appreciated!!!
