### ISSUE TITLE
Gather content for new Web Fellows site

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#63]
We should include (assuming  there are no adjustments needed, @Melechuga please let us know if otherwise):
- FAQs content from https://advocacy.mozilla.org/faq/
- Benefits content from https://advocacy.mozilla.org/benefits/ if
- Assuming we'll want to link to last year's cohorts, found here: https://advocacy.mozilla.org/open-web-fellows/

We will need:
- Updated host organizations, last year's are here: https://advocacy.mozilla.org/host-organizations/ – Including vector logos
- some updated intro/narrative around the program for the landing page/section.

Kickoff meeting notes are here for reference: https://public.etherpad-mozilla.org/p/webfellowsupdate

@Melechuga assigning to you. Can you post your draft or finalized copy here when you're ready?

**Comment by kristinashu** [comment]
Would we be open to removing the FAQ section? FAQ pages generally aren't the best user experience because they're such a hodge podge of info with no real organization or hierarchy. Ideally the main website content should cover any questions we expect a user to have. Open News (https://opennews.org/what/fellowships/info/) covers a lot of the types of questions we have with sections like 'What is a Fellowship?' and 'Who can become a fellow?' We could also include a section with more detail about the application process. This way, it will be easier for users to scan the info and we can ditch the FAQ page. Thoughts?

**Comment by cassiemc** [comment]
I like that proposal @kristinashu

**Comment by Melechuga** [comment]
That sounds good @kristinashu. Thanks for pointing out OpenNews' approach; I've started editing the FAQ in the website in this google doc: (https://docs.google.com/a/mozilla.com/document/d/16DPpk9dlB7YJyahjwA6Dk3h4bmNLjc2BmUDUr690oZg/edit?usp=sharing). Edits appreciated!

**Comment by cassiemc** [comment]
Left some comments in the doc, getting closer @Melechuga, thanks!

**Comment by kristinashu** [comment]
I believe copy will be finalized this Wednesday. 

@Melechuga we'll also need vector logos from each org. I was able to get University of Toronto's logo online but that's it.

**Comment by Melechuga** [comment]
@kristinashu Yup, we've asked all host orgs to send us hi-res official vector logos by this Friday. Does that timing work for you?

**Comment by kristinashu** [comment]
Yup sounds good, thanks @Melechuga!

**Comment by cassiemc** [comment]
@Melechuga Closing this ticket. Please file new ones if you have new copy changes :)
