### ISSUE TITLE
IA for advocacy site

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/movement-building#72]
Here is the proposed information architecture for the advocacy site: https://redpen.io/p/hq89c0dea3bab99fb0

![2xadvocacy-ia-01](https://cloud.githubusercontent.com/assets/1068783/12207608/7ab5cbec-b5fc-11e5-9836-09a418d05adb.jpg)

Things that are still up in the air: 
- should we have a blog of Advocacy and another separate one for Open Web Fellows or should we use tags to filter?
- what is on the home page?
- are we sticking with the name 'open web fellows'?

Note: we are getting rid of the Get Involved Page.

cc @brettgaylor @Melechuga @davidascher @cassiemc

**Comment by cassiemc** [comment]
- I think having two blogs nested in the same architecture is odd, and would recommend using tags on the policy blog (if we have full posting access) until we get the wider IA/url structure sorted out for advocacy.
- I'm not attached to the idea but wonder if we could use shorter verbiage, ie 'web fellows' instead of 'open web fellows'? @brettgaylor @Melechuga 
- As for homepage, I really like what you have in the UX, @kristinashu. https://redpen.io/un8711a4a1b5fe588e

**Comment by kristinashu** [comment]
@cassiemc I definitely agree with your blog suggestion. I've updated the IA https://redpen.io/p/hq89c0dea3bab99fb0
@ScottDowne is it possible to add tags to the Advocacy and Policy Blog (https://blog.mozilla.org/netpolicy/)?

I also like 'web fellows' but will hold off on making that update. I think @brettgaylor and @Melechuga are currently brainstorming new names?

**Comment by kristinashu** [comment]
We're sticking with "Open Web Fellows" as the name.

![2xadvocacy-ia-02](https://cloud.githubusercontent.com/assets/1068783/12367958/981e4818-bb9b-11e5-8886-d3b3e002a65d.jpg)
