### ISSUE TITLE
Figure out blog url for advocacy.mozilla.org

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#75]
Currently, the blog posts on Advocacy.mozilla.org link to https://blog.mozilla.org/netpolicy/

Note: in the new designs, we are moving the blog url into the main nav, so it will have a bit more prominence than its current incantation (posts are linked individually toward the bottom of the page).

Is this still an ideal blog url? We could potentially set up a filter to only show urls with specific tags, but not sure if that's necessary. @HPaulJohnson @KevZawacki @Melechuga 

cc @ScottDowne

**Comment by valianttry** [comment]
Q -- is this blog about Fellows, about our campaign strategy, or a home for our encryption blogs? There are quite a few conversations happening about blogs lately.... I want to make sure we're on same page. :)

**Comment by Melechuga** [comment]
IIRC, the idea is for the "fellows blog" to link to a categorized/curated list of blogposts specifically about the fellows from the netpolicy blog. For example: https://blog.mozilla.org/netpolicy/tag/open-web-fellows/ The reason is that there isn't a lot of traffic driven to the blog site, but rather to individual posts. Retroactively tagging relevant blogposts is on my "to do" list for the week (^.^) 

cc @valianttry

**Comment by cassiemc** [comment]
@Melechuga @valianttry This ticket could definitely use some clarity!

Since our finalization of the URL for open web fellows work, and with rebuilding the advoacy.mozilla.org homepage, I am not sure this makes sense to link to a filtered list anymore. The blog link is in the main nav, so users would likely expect it to relate to 'advocacy' as a whole.

@Melechuga if you still need a filtered list for open web fellows, perhaps we can link to a filtered view of that blog within the text somewhere on those subpages?

Otherwise, am closing this so as not to create extra unnecessary work.
